"use client";
import {useState,useMemo,useEffect} from 'react';
import {geoMercator,geoPath,geoGraticule} from 'd3-geo';
import {Globe2,BookOpen,ShieldCheck,ArrowRight,Triangle,Pause,Play,Sun,Mountain,Leaf,Waves,House,Backpack,MoveRight,Maximize} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import region from '@/lib/indonesia-region.json';
import './geography.css';

const volcanoes=[
 {name:'Kerinci',point:[101.2667,-1.6917],region:'Sumatra',source:'https://geologi.esdm.go.id/perpustakaan/?id=20354&keywords=&p=show_detail'},
 {name:'Krakatau',point:[105.4233,-6.1009],region:'Selat Sunda',source:'https://volcano.si.edu/volcano.cfm?vn=262000'},
 {name:'Tambora',point:[118,-8.25],region:'Sumbawa',source:'https://volcano.si.edu/volcano.cfm?vn=264040'},
 {name:'Banda Api',point:[129.881,-4.523],region:'Kepulauan Banda',source:'https://volcano.si.edu/volcano.cfm?vn=265090'},
 {name:'Lokon-Empung',point:[124.7992,1.3644],region:'Sulawesi Utara',source:'https://volcano.si.edu/volcano.cfm?vn=266100'},
 {name:'Dukono',point:[127.8783,1.6992],region:'Halmahera',source:'https://volcano.si.edu/volcano.cfm?vn=268010'},
];
const islands=[{name:'SUMATRA',point:[100,2.4]},{name:'JAWA',point:[111,-6]},{name:'KALIMANTAN',point:[114,1.3]},{name:'SULAWESI',point:[121.1,-3.9]},{name:'PAPUA',point:[137,-3.3]},{name:'NUSA TENGGARA',point:[119,-10.4]},{name:'MALUKU',point:[130.4,-1.9]}];
export default function GeographyHome({section='home'}:{section?:'home'|'belajar'|'mitigasi'}){
 const [fullscreen,setFullscreen]=useState(false),[fullscreenError,setFullscreenError]=useState('');
 useEffect(()=>{const sync=()=>setFullscreen(!!document.fullscreenElement);sync();document.addEventListener('fullscreenchange',sync);return ()=>document.removeEventListener('fullscreenchange',sync);},[]);
 async function toggleFullscreen(){try{setFullscreenError('');if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setFullscreenError('Layar penuh belum tersedia. Gunakan tombol layar penuh pada browser papan.');}}
 return <div className={'geo-home '+(section==='home'?'is-home':section==='belajar'?'is-learning':'')}>
 {section==='home'&&<div className="home-fullscreen"><Button variant="ghost" onClick={toggleFullscreen} aria-label={fullscreen?'Keluar layar penuh':'Layar penuh'} aria-pressed={fullscreen}><Maximize/><span>{fullscreen?'Keluar layar penuh':'Layar penuh'}</span></Button>{fullscreenError&&<p role="status">{fullscreenError}</p>}</div>}
 {section!=='home'&&<header className="geo-nav"><a className="geo-brand" href="/"><span><Globe2/></span><div>Nusantara<span>JELAJAH • PAHAMI • SIAGA</span></div></a><nav aria-label="Menu utama"><a href="/belajar" aria-current={section==='belajar'?'page':undefined}>Belajar</a><a href="/mitigasi" aria-current={section==='mitigasi'?'page':undefined}>Mitigasi Gempa</a></nav><Button asChild variant="outline"><a href="/lab"><Triangle/>Laboratorium <ArrowRight/></a></Button></header>}
 {section==='home'?<>
 <section className="geo-intro"><div className="geo-kicker"><span/> IPAS · KELAS 6</div><h1>Mengenal Kondisi Geografis Indonesia <span>(Manfaat dan Ancaman)</span></h1><p>Kenali negeri kita. Temukan kekayaan alamnya, pahami risikonya,<br className="desktop-break"/> dan belajar menjadi generasi yang siap siaga.</p><nav className="hero-glass-menu" aria-label="Pilih kegiatan"><a href="/belajar"><BookOpen/>Belajar</a><a href="/mitigasi"><ShieldCheck/>Mitigasi Gempa</a><a href="/lab"><Triangle/>Lab Maya</a></nav></section>


 </>:section==='belajar'?<Learning/>:<Mitigation/>}
 <footer className="geo-footer"><span>Belajar mengenal alam. Berlatih menghadapi tantangan.</span><div><a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Peta: Natural Earth</a><a href="https://volcano.si.edu/" target="_blank" rel="noreferrer">Gunung api: Smithsonian GVP</a><a href="https://pubs.usgs.gov/gip/dynamic/fire.html" target="_blank" rel="noreferrer">Cincin Api: USGS</a></div></footer>
 </div>;
}

function LearningMap({topic}:{topic:"equator"|"fire"}){
 const [paused,setPaused]=useState(false),[selected,setSelected]=useState<number|null>(null);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setPaused(mq.matches);},[]);
 const map=useMemo(()=>{const indonesia=region.features.find(f=>f.properties.id==='IDN')!;const projection=geoMercator().fitExtent([[45,48],[1155,445]],indonesia as any);const path=geoPath(projection);return {projection,path,graticule:path(geoGraticule().extent([[90,-18],[149,12]]).step([5,5])()),equator:path({type:'LineString',coordinates:[[91,0],[145,0]]}),arcs:[path({type:'LineString',coordinates:volcanoes.slice(0,4).map(v=>v.point)}),path({type:'LineString',coordinates:volcanoes.slice(4).map(v=>v.point)})]};},[]);
 const fire=topic==="fire",equator=!fire;
 return ( <section className={'geo-map-section '+(paused?'is-paused':'')} aria-label="Peta interaktif Indonesia"><div className="geo-map-head"><div><span className="geo-kicker">JELAJAHI PETA</span><h2>{fire?'Jalur Cincin Api':'Garis Khatulistiwa'}</h2></div><div className="map-controls"><Button variant="ghost" aria-label={paused?'Putar animasi':'Jeda animasi'} onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</Button></div></div>
 <div className="geo-map-scroll"><div className="geo-map-inner"><svg viewBox="0 0 1200 490" className="indonesia-map" role="img" aria-labelledby="map-title map-description"><title id="map-title">{fire?'Peta Indonesia dan contoh gunung api dalam jalur Cincin Api':'Peta Indonesia dilintasi khatulistiwa'}</title><desc id="map-description">{fire?'Enam contoh gunung api. Garis penghubung skematis, bukan batas lempeng atau peta bahaya.':'Garis khatulistiwa berada pada lintang nol derajat.'}</desc><defs><clipPath id="map-clip"><rect width="1200" height="490"/></clipPath></defs><g clipPath="url(#map-clip)"><path d={map.graticule||''} className="map-graticule"/>{region.features.map(f=><path key={f.properties.id} d={map.path(f as any)||''} className={f.properties.id==='IDN'?'map-land':'map-neighbor'}/>)}
 {equator&&<g className="equator"><path d={map.equator||''}/><text x="1100" y={(map.projection([140,0])?.[1]||0)-14} textAnchor="end">KHATULISTIWA · 0°</text></g>}
 {fire&&<g className="fire-paths">{map.arcs.map((d,i)=><g key={i}><path className="fire-glow" d={d||''}/><path className="fire-route" d={d||''}/></g>)}</g>}
 {islands.map(i=>{const p=map.projection(i.point as [number,number])!;return <text key={i.name} x={p[0]} y={p[1]} className="island-label" textAnchor="middle">{i.name}</text>})}<text x="135" y="405" className="ocean-label">SAMUDRA HINDIA</text><text x="990" y="78" className="ocean-label">SAMUDRA PASIFIK</text>
 {fire&&volcanoes.map((v,i)=>{const p=map.projection(v.point as [number,number])!;return <g key={v.name} transform={`translate(${p[0]},${p[1]})`}><circle r="12" className="volcano-pulse" style={{animationDelay:`${i*.4}s`}}/><circle r="5" className="volcano-center"/></g>})}</g></svg>
 {fire&&volcanoes.map((v,i)=>{const p=map.projection(v.point as [number,number])!;return <button key={v.name} className={'volcano-hit '+(selected===i?'chosen':'')} style={{left:p[0]/12+'%',top:p[1]/4.9+'%'}} aria-label={`Pelajari Gunung ${v.name}, ${v.region}`} aria-pressed={selected===i} onClick={()=>setSelected(selected===i?null:i)}><span className="sr-only">{v.name}</span></button>})}</div></div>
 <div className="geo-map-footer"><div className="map-legend"><span><i className="legend-land"/>Daratan Indonesia</span>{fire&&<span><i className="legend-fire"/>Cincin Api · contoh gunung api</span>}{equator&&<span><i className="legend-equator"/>Khatulistiwa</span>}</div><p role="status">{selected!==null&&fire?<><strong>{volcanoes[selected].name}</strong> · {volcanoes[selected].region} · <a href={volcanoes[selected].source} target="_blank" rel="noreferrer">Kenali gunung ini ↗</a></>:fire?'Ketuk titik merah untuk mengenal gunung api.':'Lintang 0° membagi Bumi menjadi belahan utara dan selatan.'}</p></div>
 {fire&&<p className="map-caption">Cuplikan jalur Cincin Api di Indonesia. Garis menghubungkan beberapa contoh gunung api secara skematis; bukan batas lempeng, status aktivitas, atau peta risiko.</p>}<p className="map-caption">Peta: Natural Earth · Gunung api: Smithsonian GVP</p></section>);
}
function Learning(){
 const [slide,setSlide]=useState(0);
 const titles=['Dilintasi Khatulistiwa','Jalur Cincin Api','Negeri Kepulauan'];
 return <section className={'learning-deck slide-theme-'+slide} aria-label="Slide Kondisi Geografis Indonesia" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();setSlide(s=>Math.min(2,s+1));}if(e.key==='ArrowLeft'){e.preventDefault();setSlide(s=>Math.max(0,s-1));}}}>
 <div className="slide-top"><a href="/">← Beranda</a><span>Belajar · {slide+1} / 3</span></div>
 <h1>Kondisi Geografis Indonesia</h1>
 <div className={"slide-body "+(slide<2?"has-map":"")}>
 {slide===0&&<article className="slide-glass"><Sun/><h2>Dilintasi Khatulistiwa</h2><p>Khatulistiwa adalah garis khayal pada lintang 0° yang membagi Bumi menjadi belahan utara dan selatan.</p><h3>Manfaat</h3><p>Sinar Matahari sepanjang tahun mendukung kehidupan tropis dan kegiatan pertanian.</p><h3>Yang perlu diwaspadai</h3><p>Hujan lebat dapat memicu banjir dan longsor. Musim dan hujan juga dipengaruhi angin, laut, serta kondisi setempat.</p></article>}
{slide===1&&<article className="slide-glass"><Mountain/><h2>Jalur Cincin Api</h2><p>Cincin Api merupakan kawasan yang banyak mengalami gempa dan aktivitas gunung api di sekitar Samudra Pasifik.</p><h3>Manfaat</h3><p>Material vulkanik yang melapuk dapat menyuburkan tanah. Panas dari dalam Bumi juga dapat dimanfaatkan sebagai energi.</p><h3>Yang perlu diwaspadai</h3><p>Gempa dan letusan gunung api dapat membahayakan permukiman. Sebagian gempa bawah laut dapat memicu tsunami.</p></article>}
{slide===2&&<article className="slide-glass"><Waves/><h2>Negeri Kepulauan</h2><p>Laut menghubungkan banyak pulau dengan ragam bentang alam dan kehidupan.</p><h3>Manfaat</h3><p>Sumber daya laut, jalur pelayaran, dan wisata alam mendukung kehidupan masyarakat.</p><h3>Yang perlu diwaspadai</h3><p>Wilayah pesisir perlu mengenali ancaman tsunami dan abrasi, serta menjaga ekosistem pantai.</p></article>}
 {slide<2&&<LearningMap key={slide} topic={slide===0?"equator":"fire"}/>}
 </div>
 <nav className="slide-navigation" aria-label="Navigasi slide"><Button variant="ghost" disabled={slide===0} onClick={()=>setSlide(slide-1)}>← Sebelumnya</Button><div className="slide-selectors">{titles.map((title,i)=><button key={title} onClick={()=>setSlide(i)} aria-label={`Slide ${i+1}: ${title}`} aria-current={slide===i?'step':undefined}>{i+1}</button>)}</div><Button variant="ghost" disabled={slide===2} onClick={()=>setSlide(slide+1)}>Berikutnya →</Button></nav>
 </section>
}
function LightPrompt(){return <Leaf aria-hidden="true"/>}
function Mitigation(){return <section className="geo-lesson"><a href="/" className="back-home">← Kembali ke beranda</a><span className="geo-kicker">MITIGASI GEMPA</span><h1>Kenali risikonya.<br/>Latih kesiapsiagaannya.</h1><p className="lesson-intro">Mitigasi adalah upaya mengurangi risiko bencana. Mulailah dari lingkungan terdekat dan berlatihlah bersama guru serta keluarga.</p><Tabs defaultValue="sebelum" className="mitigation-tabs"><TabsList aria-label="Tahapan kesiapsiagaan"><TabsTrigger value="sebelum">Sebelum gempa</TabsTrigger><TabsTrigger value="saat">Saat gempa</TabsTrigger><TabsTrigger value="sesudah">Sesudah gempa</TabsTrigger></TabsList><TabsContent value="sebelum"><div className="safety-content"><Backpack/><div><h2>Siapkan, kenali, dan berlatih.</h2><ol><li>Kenali tempat berlindung, jalur evakuasi, dan titik kumpul sekolah.</li><li>Bersama orang dewasa, amankan lemari dan letakkan benda berat di bawah.</li><li>Siapkan perlengkapan darurat: air, makanan, senter, serta kotak P3K.</li></ol></div></div></TabsContent><TabsContent value="saat"><div className="safety-content"><ShieldCheck/><div><h2>Lindungi diri dari benda yang jatuh.</h2><ol><li>Di dalam ruangan, merunduk, lindungi kepala dan leher, lalu berlindung di bawah meja kokoh dan berpegangan.</li><li>Jauhi kaca. Jangan menggunakan lift. Ikuti arahan guru.</li><li>Di luar, jauhi bangunan, tiang, dan pohon. Di pesisir, setelah guncangan kuat atau lama berhenti, segera evakuasi ke tempat tinggi melalui jalur aman.</li></ol></div></div></TabsContent><TabsContent value="sesudah"><div className="safety-content"><House/><div><h2>Keluar tertib dan tetap waspada.</h2><ol><li>Setelah guncangan berhenti, ikuti jalur aman menuju titik kumpul bersama guru.</li><li>Laporkan orang yang terluka kepada orang dewasa. Hindari bangunan yang rusak.</li><li>Waspadai gempa susulan dan ikuti informasi resmi BMKG serta petugas.</li></ol></div></div></TabsContent></Tabs><p className="safety-source">Panduan pembelajaran diringkas dari <a href="https://www.bmkg.go.id/gempabumi/mitigasi/antisipasi-gempabumi" target="_blank" rel="noreferrer">BMKG: Antisipasi Gempa Bumi</a>. Sesuaikan latihan dengan prosedur sekolah.</p><div className="lab-invitation"><span className="lab-invitation-icon"><Triangle/></span><div><span className="geo-kicker">LANJUTKAN DENGAN EKSPERIMEN</span><h2>Bisakah menaramu bertahan?</h2><p>Bangun dari nol menggunakan marshmallow dan tusuk gigi virtual. Uji guncangan, lalu perbaiki desainmu.</p></div><Button asChild><a href="/lab">Masuk aplikasi <ArrowRight/></a></Button></div><p className="model-note">Laboratorium adalah model pembelajaran struktur sederhana, bukan pengujian keamanan bangunan nyata.</p></section>}
