"use client";
import {useEffect,useState} from 'react';
import Scene from './tower-scene';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Box,Rotate3D,Plus,Link2,Move,Trash2,Undo2,Redo2,Ruler,Play,Maximize,Users,BookOpen,History,Triangle,Square,ZoomIn,ZoomOut,GraduationCap,Download,Check,ArrowRight,Layers,Lightbulb,RotateCcw,House} from 'lucide-react';
import {preset,height,validDesign,type Design,type Result} from '@/lib/tower';
type Session={token:string,role:string,code?:string,name:string,challenge?:string,strength?:string};
const tools=[['orbit','Putar',Rotate3D],['add','Titik',Plus],['connect','Sambung',Link2],['move','Geser',Move],['delete','Hapus',Trash2]] as const;
const help:Record<string,string>={orbit:'Geser satu jari untuk memutar. Cubit dua jari untuk memperbesar.',add:'Ketuk petak untuk menambah titik. Lingkaran merah samar menandai posisi titik di bawah.',connect:'Ketuk dua marshmallow untuk menyambungkan tusuk gigi.',move:'Seret marshmallow pada bidang tingkat yang sama.',delete:'Ketuk marshmallow untuk menghapusnya beserta sambungannya.'};
export async function api(action:string,data:any={}){const r=await fetch('/api/lab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const v:any=await r.json();if(!r.ok)throw new Error(v.error||'Belum dapat terhubung. Coba lagi.');return v;}
function Choice({value,onChange,values,label}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map((v:string)=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function TowerApp(){
 const [fullscreen, setFullscreen] = useState(false);
 useEffect(() => {
  const handleFullscreenChange = () => setFullscreen(!!document.fullscreenElement);
  document.addEventListener('fullscreenchange', handleFullscreenChange);
  return () => document.removeEventListener('fullscreenchange', handleFullscreenChange);
 }, []);
 const [design,setDesign]=useState<Design>(()=>({nodes:[],beams:[]})),[past,setPast]=useState<Design[]>([]),[future,setFuture]=useState<Design[]>([]),[tool,setTool]=useState('add'),[selected,setSelected]=useState<number|null>(null),[level,setLevel]=useState(0),[view,setView]=useState('3/4'),[zoom,setZoom]=useState(1),[low,setLow]=useState(false),[wire,setWire]=useState(false),[mode,setMode]=useState('Bebas'),[strength,setStrength]=useState('Ringan'),[direction,setDirection]=useState('X-Y'),[run,setRun]=useState(0),[time,setTime]=useState(0),[result,setResult]=useState<Result|null>(null),[history,setHistory]=useState<Result[]>([]),[panel,setPanel]=useState(''),[message,setMessage]=useState('Mulai dari idemu sendiri. Ketuk petak untuk menambahkan marshmallow, lalu sambungkan titik-titiknya.'),[name,setName]=useState('Kelompok 1'),[session,setSession]=useState<Session|null>(null),[busy,setBusy]=useState(false),[reflection,setReflection]=useState(''),[className,setClassName]=useState('Kelas 6 — Eksperimen Gempa'),[code,setCode]=useState(''),[students,setStudents]=useState<any[]>([]),[classResults,setClassResults]=useState<Result[]>([]),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const s=sessionStorage.getItem('tower-session');if(s){const v=JSON.parse(s);setSession(v);setName(v.name);api('history',{token:v.token}).then(x=>setHistory(x.results)).catch(e=>setMessage(e.message));}}catch{}},[]);
 useEffect(()=>{if(panel!=='guru'||session?.role!=='teacher')return;const refresh=()=>api('dashboard',{token:session.token}).then(x=>{setStudents(x.students);setClassResults(x.results);}).catch(e=>setMessage(e.message));refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t);},[panel,session]);
 function edit(next:Design){if(run&&!result)return;if(!validDesign(next)){setMessage('Batas area: 80 marshmallow, 240 tusuk gigi, dan tinggi 48 cm.');return;}setRun(0);setPast(p=>[...p.slice(-29),design]);setFuture([]);setDesign(next);setSelected(null);setResult(null);setSaved(false);}
 function node(id:number){if(tool==='delete'){edit({nodes:design.nodes.filter(n=>n.id!==id),beams:design.beams.filter(b=>b.a!==id&&b.b!==id)});return;}if(tool==='connect'){if(selected===null){setSelected(id);setMessage('Sekarang ketuk marshmallow kedua.');}else if(selected!==id){const exists=design.beams.some(b=>(b.a===id&&b.b===selected)||(b.b===id&&b.a===selected));if(!exists)edit({...design,beams:[...design.beams,{a:selected,b:id}]});setSelected(null);setMessage(exists?'Dua titik ini sudah tersambung.':'Tusuk gigi tersambung.');}}}
 function place(x:number,y:number,z:number,id?:number){if(Math.abs(x)>4||Math.abs(z)>4){setMessage('Tempatkan titik di dalam meja.');return;}if(design.nodes.some(n=>n.id!==id&&n.x===x&&n.y===y&&n.z===z)){setMessage('Sudah ada marshmallow di titik itu.');return;}edit({...design,nodes:id===undefined?[...design.nodes,{id:Math.max(-1,...design.nodes.map(n=>n.id))+1,x,y,z}]:design.nodes.map(n=>n.id===id?{...n,x,y,z}:n)});}
 async function ensureSession(){if(session)return session;const s=await api('start',{name:name.trim()||'Kelompok 1'});setSession(s);sessionStorage.setItem('tower-session',JSON.stringify(s));return s;}
 async function save(r:Result){setBusy(true);try{const s=await ensureSession();await api('save',{token:s.token,result:r});setSaved(true);setMessage('Percobaan tersimpan.');}catch(e:any){setMessage(e.message+' Hasil masih tersedia di layar; tekan Simpan lagi.');}finally{setBusy(false);}}
 function done(duration:number,standing:boolean){const r:Result={id:crypto.randomUUID(),name,height:height(design),strength,direction,duration:Math.round(duration*10)/10,score:Math.round(duration*10),standing,date:new Date().toISOString(),design};setResult(r);setHistory(h=>[r,...h]);setTime(10);setReflection('');save(r);}
 function start(){if(design.nodes.length<4||!design.nodes.some(n=>n.y>0)||design.beams.length<3){setMessage('Buat menara dengan titik di atas dasar dan minimal 3 sambungan.');return;}setSelected(null);setResult(null);setSaved(false);setTime(0);setRun(Date.now());setMessage('Amati gerakan menara selama 10 detik.');}
 async function enter(action:string){setBusy(true);try{const s=await api(action,{name:name.trim(),code:code.toUpperCase().trim(),className,challenge:mode,strength});setSession(s);sessionStorage.setItem('tower-session',JSON.stringify(s));setHistory([]);setName(s.name);if(s.challenge)setMode(s.challenge);if(s.strength)setStrength(s.strength);setMessage(action==='create'?'Kelas berhasil dibuat.':'Berhasil bergabung ke kelas.');if(action==='join')setPanel('');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 function csv(rows:Result[]){const esc=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const text='\uFEFF'+[['Nama','Tanggal','Tinggi (cm)','Gempa','Arah','Bertahan (detik)','Skor','Hasil','Refleksi'],...rows.map(r=>[r.name,r.date,r.height,r.strength,r.direction,r.duration,r.score,r.standing?'Berdiri':'Roboh',r.reflection||''])].map(row=>row.map(esc).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='hasil-toothpick-tower.csv';a.click();URL.revokeObjectURL(u);}
 return <main className="lab">
 <div style={{position:'absolute',top:'18px',right:'18px',zIndex:50,display:'flex',gap:'10px'}}>
  <Button asChild variant="ghost" style={{color:'white',background:'rgba(8,39,59,.48)',border:'1px solid #ffffff90',borderRadius:'14px',backdropFilter:'blur(14px)',WebkitBackdropFilter:'blur(14px)'}}><a href="/"><House aria-label="Kembali ke Beranda"/></a></Button>
  <Button variant="ghost" style={{color:'white',background:'rgba(8,39,59,.48)',border:'1px solid #ffffff90',borderRadius:'14px',backdropFilter:'blur(14px)',WebkitBackdropFilter:'blur(14px)'}} onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setMessage('Gunakan pintasan browser.');}}} aria-label={fullscreen?'Keluar layar penuh':'Layar penuh'}>{fullscreen?<Maximize aria-label="Keluar layar penuh"/>:<Maximize aria-label="Layar penuh"/>}</Button>
 </div>
 <div className="workspace-head" style={{paddingTop: '24px'}}><div><h2 style={{display:'flex',alignItems:'center',gap:'12px',color:'white',marginTop:'0'}}><img src="/stem-logo.png" alt="STEM" style={{height:'36px',objectFit:'contain',marginBottom:'4px',display:'block'}}/>Lab Maya Struktur Anti Gempa</h2></div><div className="session-label"><Users size={20}/><input aria-label="Nama kelompok" value={name} maxLength={40} disabled={!!session||!!run} onChange={e=>setName(e.target.value)}/>{session?.code&&<span>{session.code}</span>}</div></div>
 <div className="workspace"><aside className="build-panel"><div className="step-title"><span>01</span><h3>Bangun menaramu</h3></div><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger disabled={!!run} value="Bebas">Bebas</TabsTrigger><TabsTrigger disabled={!!run} value="Tantangan">Tantangan</TabsTrigger></TabsList></Tabs>
 {mode==='Bebas'&&<div className="challenge" style={{background:'#f6f8fc',border:'1px dashed #dbe4ee'}}><strong>Mode bebas</strong><p>Eksplorasi tanpa batas. Uji berbagai bentuk tanpa batasan bahan.</p></div>}
 {mode==='Tantangan'&&<div className="challenge"><strong>Misi: tinggi & tangguh</strong><p>Bangun ≥18 cm, gunakan ≤50 tusuk gigi, dan bertahan 10 detik.</p></div>}
 <label className="section-label">CONTOH OPSIONAL</label><div className="preset-grid"><Button disabled={!!run} variant="outline" onClick={()=>edit(preset(true))}><Triangle/><span>Segitiga<small>Dengan penguat</small></span></Button><Button disabled={!!run} variant="outline" onClick={()=>edit(preset(false,3,false))}><Square/><span>Segi empat<small>Tanpa penguat</small></span></Button></div>
 <label className="section-label">ALAT BANGUN</label><div className="tool-grid">{tools.map(([id,label,Icon])=><Button key={id} disabled={!!run} variant="outline" aria-pressed={tool===id} className={tool===id?'active':''} onClick={()=>{setTool(id);setSelected(null);}}><Icon/>{label}</Button>)}</div>
 <div className="level-row"><label>Tingkat titik baru</label><div><Button aria-label="Turunkan tingkat" disabled={level===0||!!run} variant="outline" onClick={()=>setLevel(level-1)}>−</Button><strong>{level}</strong><Button aria-label="Naikkan tingkat" disabled={level===8||!!run} variant="outline" onClick={()=>setLevel(level+1)}>+</Button></div><small>{level*6} cm dari dasar</small></div>
 <div className="materials"><div><span className="material-dot wood"/>Tusuk gigi<strong>{design.beams.length}<small> / 240</small></strong></div><div><span className="material-dot"/>Marshmallow<strong>{design.nodes.length}<small> / 80</small></strong></div></div>
 <div className="undo-row"><Button aria-label="Urungkan" disabled={!past.length||!!run} variant="outline" onClick={()=>{setFuture([design,...future]);setDesign(past[past.length-1]);setPast(past.slice(0,-1));setSelected(null);setResult(null);}}><Undo2/></Button><Button aria-label="Ulangi" disabled={!future.length||!!run} variant="outline" onClick={()=>{setPast([...past,design]);setDesign(future[0]);setFuture(future.slice(1));setSelected(null);setResult(null);}}><Redo2/></Button><Button disabled={!!run} variant="ghost" onClick={()=>edit({nodes:[],beams:[]})}><RotateCcw/>Kosongkan</Button></div></aside>
 <section className="canvas-panel"><div className="canvas-top"><span><Box size={17}/> Meja eksperimen 3D</span><span className="canvas-badge">{run&&!result?'Gempa berlangsung':result?'Uji selesai':'Mode membangun'}</span></div><Scene design={design} tool={tool} level={level} selected={selected} low={low} wire={wire} view={view} zoom={zoom} run={run} strength={strength} direction={direction} onNode={node} onPlace={place} onProgress={setTime} onDone={done}/><div className="camera-tools"><div>{['Depan','Atas','3/4'].map(v=><Button key={v} variant="outline" aria-pressed={view===v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</Button>)}</div><div><Button aria-label="Perkecil" variant="outline" onClick={()=>setZoom(Math.max(.6,zoom-.2))}><ZoomOut/></Button><Button aria-label="Perbesar" variant="outline" onClick={()=>setZoom(Math.min(2.5,zoom+.2))}><ZoomIn/></Button></div></div><div className="canvas-hint"><Move size={18}/>{run?'Kamera tetap dapat diputar saat pengujian.':help[tool]}</div><div className="canvas-settings"><label><Switch checked={wire} disabled={!!run} onCheckedChange={setWire}/>Lihat rangka</label><label><Switch checked={low} onCheckedChange={setLow}/>Grafis ringan</label><span>1 petak = 2 cm</span></div></section>
 <aside className="test-panel"><div className="step-title"><span>02</span><h3>Uji ketangguhan</h3></div><div className="height-card"><Ruler/><span>Tinggi menara<strong>{height(design)}<small>cm</small></strong></span><Button variant="ghost" onClick={()=>setMessage('Tinggi menara saat ini '+height(design)+' cm. Diukur dari dasar hingga sambungan tertinggi.')} aria-label="Ukur tinggi"><ArrowRight/></Button></div><label className="section-label">KEKUATAN GUNCANGAN</label><div className="strengths">{['Ringan','Sedang','Kuat'].map((s,i)=><Button key={s} disabled={!!run} variant="outline" aria-pressed={strength===s} className={strength===s?'active':''} onClick={()=>setStrength(s)}><span className="bars">{'▂▄▆'.slice(0,i+1)}</span>{s}</Button>)}</div><label className="section-label">ARAH GUNCANGAN</label><Choice label="Arah guncangan" value={direction} onChange={setDirection} values={run?[direction]:['X','X-Y']}/><p className="micro">{direction==='X-Y'?'Dua arah mendatar: kiri–kanan dan depan–belakang.':'Satu arah mendatar: kiri–kanan.'}</p><div className="duration"><span>Durasi pengujian</span><strong>10 detik</strong></div>
 <Button className="simulate" disabled={!!run&&!result} onClick={()=>{if(result){setRun(0);setResult(null);setMessage('Desain dipulihkan. Perbaiki sebelum menguji lagi.');}else start();}}>{result?<RotateCcw/>:<Play/>}{result?'Perbaiki desain':run?'Sedang menguji…':'Simulasikan gempa'}</Button>{!!run&&<div className="progress"><div style={{width:Math.min(100,time*10)+'%'}}/><span>{Math.min(10,time).toFixed(1)} / 10 detik</span></div>}
 {result?<div className={'result-card '+(result.standing?'success':'retry')} aria-live="polite"><strong>{result.standing?'Menara bertahan!':'Coba perkuat lagi'}</strong><div><b>{result.score}<small>/100</small></b><span>Bertahan<br/>{result.duration} detik</span></div>{mode==='Bebas'&&<p style={{color:result.standing?'#23654b':'#9b5427'}}>{result.standing?'Desain yang bagus! Eksplorasi bentuk lainnya.':'Analisis bagian yang lemah dan perkuat.'}</p>}{mode==='Tantangan'&&<p>{result.standing&&result.height>=18&&design.beams.length<=50?'Misi berhasil!':'Misi belum tercapai. Periksa tinggi, bahan, dan ketahanan.'}</p>}<Button variant="outline" onClick={()=>setPanel('refleksi')}>Tulis refleksi</Button>{!saved&&<Button disabled={busy} variant="ghost" onClick={()=>save(result)}>Simpan lagi</Button>}</div>:<div className="science-note"><Lightbulb/><strong>Mengapa segitiga?</strong><p>Penguat diagonal membantu rangka mempertahankan bentuk saat menerima gaya.</p></div>}
 </aside></div><footer className="bottom-bar"><p role="status">{busy?'Menyimpan / menghubungkan…':message}</p><div><Button variant="ghost" onClick={()=>setPanel('belajar')}><BookOpen/>Panduan & STEM</Button><Button variant="outline" onClick={()=>setPanel('riwayat')}><History/>Riwayat <b>{history.length}</b></Button></div></footer>
 <Dialog open={!!panel} onOpenChange={o=>{if(!o)setPanel('')}}><DialogContent className="lab-dialog"><DialogTitle>{({belajar:'Belajar lewat eksperimen',riwayat:'Riwayat percobaan',guru:'Ruang guru',kelas:'Gabung kelas',refleksi:'Ceritakan penemuanmu'} as any)[panel]}</DialogTitle><DialogDescription>{panel==='guru'?'Kelola kegiatan dan hasil kelompok.':panel==='riwayat'?'Bandingkan desain pada kekuatan dan arah gempa yang sama.':'Toothpick Tower · Laboratorium STEM kelas 6'}</DialogDescription>
 {panel==='belajar'&&<div className="learning"><h3>Cara membangun di papan</h3><ol><li>Pilih menara contoh atau tekan Kosongkan.</li><li>Pilih Titik, atur tingkat, lalu ketuk petak meja.</li><li>Pilih Sambung dan ketuk dua marshmallow. Tambahkan penguat diagonal.</li><li>Pilih Putar untuk memeriksa sisi lain. Lalu uji gempa!</li></ol><div className="learning-grid"><article><strong>Sains · Titik berat</strong><p>Dasar lebar dan bagian atas yang ringan membantu menjaga titik berat tetap di atas bidang dasar.</p></article><article><strong>Rekayasa · Segitiga</strong><p>Segi empat dapat berubah bentuk. Penguat diagonal membaginya menjadi segitiga yang lebih kaku.</p></article><article><strong>Matematika · Pengukuran</strong><p>Bandingkan tinggi, jumlah bahan, dan waktu bertahan. Ubah satu hal setiap percobaan agar perbandingan adil.</p></article><article><strong>Teknologi · Model</strong><p>Ini model pembelajaran: sambungan dasar ditambatkan, batang dimodelkan sebagai penghubung jarak, dan sambungan dapat terputus. Skor = waktu bertahan ÷ 10 × 100. Roboh terdeteksi bila tinggi bagian atas turun lebih dari 40% atau penghubung putus.</p></article></div><p>Ringan, sedang, dan kuat adalah tingkat simulasi, bukan magnitudo gempa atau penilaian keamanan bangunan nyata. Saat latihan kesiapsiagaan di sekolah, ikuti arahan guru dan prosedur sekolah.</p></div>}
 {panel==='riwayat'&&<><Results rows={history} onLoad={r=>{setRun(0);edit(r.design);setPanel('');setMessage('Desain percobaan dimuat kembali.');}}/><Button disabled={!history.length} onClick={()=>csv(history)}><Download/>Unduh laporan CSV</Button></>}
 {panel==='refleksi'&&result&&<><p>Apa yang membuat desainmu bertahan atau roboh? Apa yang akan kamu ubah pada percobaan berikutnya?</p><textarea aria-label="Refleksi percobaan" maxLength={1500} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Menurut kelompok kami…"/><Button disabled={busy||!reflection.trim()} onClick={async()=>{const r={...result,reflection};setResult(r);setHistory(h=>h.map(v=>v.id===r.id?r:v));await save(r);}}>Simpan refleksi</Button><p role="status">{message}</p></>}
 {panel==='kelas'&&<><label>Nama siswa / kelompok<input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/></label><label>Kode kelas<input value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Dari guru"/></label><Button disabled={busy||!name.trim()||!code.trim()} onClick={()=>enter('join')}>Gabung kelas</Button><p role="status">{message}</p></>}
 {panel==='guru'&&(session?.role==='teacher'?<><div className="class-code"><span>Kode kelas<strong>{session.code}</strong></span><p>{className}<br/>Bagikan kode ini kepada kelompok yang membuka aplikasi.</p></div><p>{students.length} kelompok bergabung · Diperbarui setiap 5 detik</p><div className="student-list">{students.length?students.map(s=><div key={s.id}><strong>{s.name}</strong><span>{s.attempts} percobaan · {s.attempts?'skor terbaik '+s.best:'belum menguji'}</span></div>):<p>Belum ada kelompok. Siswa dapat memilih Gabung kelas.</p>}</div><Results rows={classResults}/><Button disabled={!classResults.length} onClick={()=>csv(classResults)}><Download/>Unduh hasil kelas</Button><p>Simpan kode kelas dan kunci guru untuk membuka kembali dashboard.</p><textarea aria-label="Kunci guru" readOnly value={session.token}/></>:<><label>Nama kelas<input value={className} maxLength={80} onChange={e=>setClassName(e.target.value)}/></label><div className="form-row"><Choice label="Tugas kelas" value={mode} onChange={setMode} values={['Bebas','Tantangan']}/><Choice label="Kekuatan kelas" value={strength} onChange={setStrength} values={['Ringan','Sedang','Kuat']}/></div><Button disabled={busy||!className.trim()} onClick={()=>enter('create')}><Plus/>Buat sesi kelas</Button><label>Buka kembali dengan kunci guru<input value={code} onChange={e=>setCode(e.target.value)}/></label><Button disabled={busy||!code} variant="outline" onClick={async()=>{setBusy(true);try{const s=await api('restore',{token:code});setSession(s);sessionStorage.setItem('tower-session',JSON.stringify(s));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>Buka dashboard</Button><p role="status">{message}</p></>)}
 </DialogContent></Dialog></main>;
}
function Results({rows,onLoad}:{rows:Result[],onLoad?:(r:Result)=>void}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Kelompok</th><th>Tinggi</th><th>Gempa</th><th>Bertahan</th><th>Skor</th>{onLoad&&<th>Desain</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}<small>{r.standing?'Berdiri':'Roboh'}</small></td><td>{r.height} cm</td><td>{r.strength}<small>{r.direction}</small></td><td>{r.duration} dtk</td><td><b>{r.score}</b></td>{onLoad&&<td><Button variant="outline" onClick={()=>onLoad(r)}>Muat</Button></td>}</tr>)}</tbody></table></div>:<div className="empty"><History/><h3>Belum ada percobaan</h3><p>Uji menaramu untuk melihat hasil di sini.</p></div>}


